version: '3.8'
services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "8080:80"
    volumes:
      - ./test-website:/usr/share/nginx/html      
      - ./configs/nginx/nginx.conf:/etc/nginx/nginx.conf